# Generated by Django 4.1.3 on 2023-02-21 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Diese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customername', models.CharField(default=True, max_length=200)),
                ('Telephonecontact', models.CharField(default=True, max_length=200)),
                ('Date', models.DateField(default=True)),
                ('EmployeeName', models.CharField(default=True, max_length=200)),
                ('EmployeeAddress', models.CharField(default=True, max_length=200)),
                ('Fueltype', models.CharField(default=True, max_length=200)),
                ('AmountinLitres', models.CharField(default=True, max_length=200)),
                ('UnitPrice', models.CharField(default=True, max_length=200)),
                ('TotalPrice', models.CharField(default=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EmployeeName', models.CharField(default=True, max_length=200)),
                ('BranchName', models.CharField(default=True, max_length=200)),
                ('EmployeeCOntact', models.CharField(default=True, max_length=200)),
            ],
        ),
    ]
