# Generated by Django 4.1.7 on 2023-02-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Diesel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diese',
            name='AmountinLitres',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='Customername',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='Date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='diese',
            name='EmployeeAddress',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='EmployeeName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='Fueltype',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='Telephonecontact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='TotalPrice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='diese',
            name='UnitPrice',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='BranchName',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeCOntact',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(max_length=200),
        ),
    ]
